//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuEditor {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EquipProperty {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EquipProperty() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MuEditor.EquipProperty", typeof(EquipProperty).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        internal static bool btnCancel_Locked {
            get {
                object obj = ResourceManager.GetObject("btnCancel.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        internal static bool btnOK_Locked {
            get {
                object obj = ResourceManager.GetObject("btnOK.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        internal static bool button1_Locked {
            get {
                object obj = ResourceManager.GetObject("button1.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        internal static bool button2_Locked {
            get {
                object obj = ResourceManager.GetObject("button2.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        internal static bool button3_Locked {
            get {
                object obj = ResourceManager.GetObject("button3.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        internal static bool button4_Locked {
            get {
                object obj = ResourceManager.GetObject("button4.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        internal static bool cbInlay1b_Locked {
            get {
                object obj = ResourceManager.GetObject("cbInlay1b.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        internal static bool cbInlay2b_Locked {
            get {
                object obj = ResourceManager.GetObject("cbInlay2b.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        internal static bool cbInlay3b_Locked {
            get {
                object obj = ResourceManager.GetObject("cbInlay3b.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        internal static bool cbInlay4b_Locked {
            get {
                object obj = ResourceManager.GetObject("cbInlay4b.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        internal static bool cbInlay5b_Locked {
            get {
                object obj = ResourceManager.GetObject("cbInlay5b.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        internal static bool cbInlay6b_Locked {
            get {
                object obj = ResourceManager.GetObject("cbInlay6b.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        internal static bool cboEquipExt_Locked {
            get {
                object obj = ResourceManager.GetObject("cboEquipExt.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        internal static bool cboEquipLevel_Locked {
            get {
                object obj = ResourceManager.GetObject("cboEquipLevel.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        internal static bool cboPlusLevel_Locked {
            get {
                object obj = ResourceManager.GetObject("cboPlusLevel.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        internal static bool cboPlusType_Locked {
            get {
                object obj = ResourceManager.GetObject("cboPlusType.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        internal static bool cbSetVal_Locked {
            get {
                object obj = ResourceManager.GetObject("cbSetVal.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        internal static bool chk380_Locked {
            get {
                object obj = ResourceManager.GetObject("chk380.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        internal static bool chkEquipJN_Locked {
            get {
                object obj = ResourceManager.GetObject("chkEquipJN.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        internal static bool chkEquipXY_Locked {
            get {
                object obj = ResourceManager.GetObject("chkEquipXY.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        internal static bool chkEquipZY1_Locked {
            get {
                object obj = ResourceManager.GetObject("chkEquipZY1.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        internal static bool chkEquipZY2_Locked {
            get {
                object obj = ResourceManager.GetObject("chkEquipZY2.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        internal static bool chkEquipZY3_Locked {
            get {
                object obj = ResourceManager.GetObject("chkEquipZY3.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        internal static bool chkEquipZY4_Locked {
            get {
                object obj = ResourceManager.GetObject("chkEquipZY4.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        internal static bool chkEquipZY5_Locked {
            get {
                object obj = ResourceManager.GetObject("chkEquipZY5.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        internal static bool chkEquipZY6_Locked {
            get {
                object obj = ResourceManager.GetObject("chkEquipZY6.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        internal static bool eee_Locked {
            get {
                object obj = ResourceManager.GetObject("eee.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        internal static bool gbXQ_Locked {
            get {
                object obj = ResourceManager.GetObject("gbXQ.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        internal static bool groupBox3_Locked {
            get {
                object obj = ResourceManager.GetObject("groupBox3.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        internal static bool label1_Locked {
            get {
                object obj = ResourceManager.GetObject("label1.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        internal static bool label10_Locked {
            get {
                object obj = ResourceManager.GetObject("label10.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        internal static bool label11_Locked {
            get {
                object obj = ResourceManager.GetObject("label11.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        internal static bool label12_Locked {
            get {
                object obj = ResourceManager.GetObject("label12.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        internal static bool label2_Locked {
            get {
                object obj = ResourceManager.GetObject("label2.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        internal static bool label3_Locked {
            get {
                object obj = ResourceManager.GetObject("label3.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        internal static bool label30_Locked {
            get {
                object obj = ResourceManager.GetObject("label30.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        internal static bool label31_Locked {
            get {
                object obj = ResourceManager.GetObject("label31.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        internal static bool label4_Locked {
            get {
                object obj = ResourceManager.GetObject("label4.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        internal static bool label5_Locked {
            get {
                object obj = ResourceManager.GetObject("label5.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        internal static bool label6_Locked {
            get {
                object obj = ResourceManager.GetObject("label6.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        internal static bool label7_Locked {
            get {
                object obj = ResourceManager.GetObject("label7.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        internal static bool label8_Locked {
            get {
                object obj = ResourceManager.GetObject("label8.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        internal static bool label9_Locked {
            get {
                object obj = ResourceManager.GetObject("label9.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        internal static bool txtDurability_Locked {
            get {
                object obj = ResourceManager.GetObject("txtDurability.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        internal static bool txtEquipCodes_Locked {
            get {
                object obj = ResourceManager.GetObject("txtEquipCodes.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        internal static bool txtName_Locked {
            get {
                object obj = ResourceManager.GetObject("txtName.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        internal static bool txtSN_Locked {
            get {
                object obj = ResourceManager.GetObject("txtSN.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
    }
}
